data <- read.table("household_power_consumption.txt", sep =";", header = TRUE, na.strings = "?")
data$datetime <- paste(data$Date,data$Time,sep=" ")
data$datetime <- strptime(as.character(data$datetime),format = "%d/%m/%Y %H:%M:%S")
data$Date <- as.Date(data$Date, format = "%d/%m/%Y")
days <- as.Date(c("2007/02/01","2007/02/02"),format="%Y/%m/%d")
data2 <- subset(data,Date %in% days)
png(file = "plot2.png", width = 480, height = 480)
with(data2, plot(datetime,Global_active_power, type = "l", ylab = "Global Active Power (kilowatts)", xlab = ""))
dev.off()